# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  acesso:
   image: acesso
   build:
     context: .
     dockerfile: Services/Acesso/Dockerfile
   ports:
     - 5000:5000

  fornecedor:
    image: fornecedor
    build:
      context: .
      dockerfile: Services/Fornecedor/Dockerfile
    ports:
      - 5001:5001

  cliente:
   image: cliente
   build:
     context: .
     dockerfile: Services/Cliente/Dockerfile
   ports:
     - 5002:5002

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge
